### ISSUE TITLE
Possible typo in Velu Formula

### ISSUE THREAD

**Issue by TheNeikos** [defeo/ema2017#5]
Hello!
A Colleague and I found a possible typo in the velu formula and pinpointed it down to this line: 

https://github.com/defeo/ema2017/blob/28d39639ce597e1a94a40fa58388347121967875/poly.tex#L1595

where instead of `+ b` it should say `+ 2b`.

Do you agree, and would you want a PR to fix it in case we did not make a mistake?

**Comment by defeo** [comment]
Apologies for taking so long to respond! You are absolutely right, that's a typo. The saddest thing is that I had fixed it in my local copy of the sources, and had been sitting on the commit for I don't know how many months. I just pushed an update which fixes this typo, and many others. 

I should really find some time to post these updated notes on the arXiv... Thank you very much for your patience!
